# Setup
title:        FSDT3 Teil2
tagline:      Visualisierung und Verarbeitung von Sensordaten
baseurl:      "/fsdt3"
paginate:     1
future:       true

# About/contact
author:
  name:       Christian Gradl
  url:        https://www.fhstp.ac.at/de/uber-uns/mitarbeiter-innen-a-z/gradl-christian

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
